//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrariaTrader.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int CartItemId { get; set; }
        public int CartId { get; set; }
        public int TraderItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual TraderItems TraderItems { get; set; }
    }
}
