//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrariaTrader.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerReputation
    {
        public int SellerId { get; set; }
        public Nullable<int> ReputationScore { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Sellers Sellers { get; set; }
    }
}
