//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrariaTrader.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traders()
        {
            this.TraderItems = new HashSet<TraderItems>();
            this.UserTraderReputation = new HashSet<UserTraderReputation>();
        }
    
        public int TraderId { get; set; }
        public string TraderName { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> BaseReputation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraderItems> TraderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTraderReputation> UserTraderReputation { get; set; }
    }
}
