//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrariaTrader.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReputation
    {
        public int UserId { get; set; }
        public int ReputationLevelId { get; set; }
        public Nullable<int> ReputationScore { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ReputationLevels ReputationLevels { get; set; }
        public virtual Users Users { get; set; }
    }
}
